server.port: 8888

spring:
  application.name: search-config-server
  cloud:
    config:
      server:
        git:
#          Change this URI according to your fork
          uri: https://github.com/garciafl/spring-cloud-timeouts.git
          searchPaths: gitConfig